FROM ubuntu:focal-20201008

MAINTAINER Ray C Horn "raychorn@gmail.com"

RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev

#COPY ./requirements.txt /requirements.txt

WORKDIR /

#RUN pip3 install -r requirements.txt
