FROM ubuntu:20.04

LABEL Ray C Horn "raychorn@gmail.com"

RUN apt-get update -y
RUN apt-get install -y python3-pip --fix-missing

#COPY ./requirements.txt /requirements.txt

WORKDIR /

#RUN pip3 install -r requirements.txt
