FROM ubuntu:20.04

LABEL Ray C Horn "raychorn@gmail.com"

RUN apt-get update -y
RUN apt install nodejs npm -y --fix-missing
RUN apt install build-essential -y --fix-missing
RUN npm install -g @angular/cli -y --fix-missing
